export { default as Text } from './Text'
export { default as Title } from './Title'
export { default as Image } from './Images'
export { default as Button } from './Button'
export { default as Logo } from './Logo'

export { default as Backgroundimage } from './Backgroundimage'
export { default as Footer } from './Footer'
export { default as Label } from './Label'
export { default as Input } from './Input'